/*
 Generated by typeshare 1.6.0
*/

import { UUID } from 'crypto';

export interface ToDoItem {
	id: UUID;
	title: string;
	complete: boolean;
	description: string;
}

export interface ToDoItemWithRank {
	id: UUID;
	title: string;
	complete: boolean;
	description: string;
	rank: string;
}

export interface RequestCreateToDoItem {
	title: string;
	description: string;
	dates: string[][];
}

export interface ResponseGetToDoByDate {
	items: ToDoItemWithRank[];
}

export interface RequestUpdateToDoItemCompleted {
	completed: boolean;
}
