/*
 Generated by typeshare 1.6.0
*/

import { UUID } from 'crypto';

// * Command: typeshare . --lang=typescript --output-file=../client/types/typeshare.ts

export interface ToDoItem {
	id: UUID;
	title: string;
	complete: boolean;
	description: string;
}

export interface RequestCreateToDoItem {
	title: string;
	description: string;
	dates: string[];
}

export interface ResponseGetToDoByDate {
	items: ToDoItem[];
}
